apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: default
spec:
  encryptedData:
    connection: AgCROs1yh3NocW0+ZUc9DilSbx8BHlpTKOLjSdCrWbL2MgEUo2mFvMlCs2R1Hz8AzAFFxbNVeGP7nsyGxWhBpSjchPB2WOb4qmFOyP9uEg3BHAmClV/6lzLjMixuT03amwpmHMQPFFdYotHDIifcvg67Jne5Qhjr3fyUtiXcgz2kNIGyd2wtpoVtUA1s>
    password: AgAJjghi0Ko3ysbhozHjrYN+339IBUFQt7fPx4bc/SJbaOsatlvBCD747TbhdjOs+/3N5OK+GMhxfbyE+d9fRyryyQZW2tgEdvzbk0E5Sk1n+Y7GHPqbFOQeNPk09AbNWMpdX9/BYuRac35FikOri8wB79YdrWsDCE2DJgAl37+mNg0wUxdkd6+awyuGAH>
    username: AgBABNXqnK3YmBhEHKl311ZdzjTxD8S4Ne0CrH3WIE7V9iUxkqKBO26Q1L+AcwDo8kfq7E/wrU8STBeyQOFAY3T8vAr+1KQRtE/D/fSL8Bo+mmk1pLBOVnqUQKLHU+qhmszc5R82YHzGrz6tupF4B45g10NFggOYp1JOnUk2l1V5oxnEmQEyxYYrhsY+nP>
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: default
    type: Opaque
